// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('./components/extra/Comments/box.vue')['default']
    Comment: typeof import('./components/extra/Comments/comment.vue')['default']
    Comments: typeof import('./components/extra/Comments/index.vue')['default']
    Loading: typeof import('./components/extra/Loading/index.vue')['default']
    LoadingView: typeof import('./components/extra/Loading/LoadingView.vue')['default']
    RelativeTime: typeof import('./components/extra/Time/RelativeTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValaxyAppLink: typeof import('./components/valaxy/ValaxyAppLink.vue')['default']
    ValaxyCopyright: typeof import('./components/valaxy/ValaxyCopyright.vue')['default']
    ValaxyFooter: typeof import('./components/valaxy/ValaxyFooter.vue')['default']
    ValaxyHamburger: typeof import('./components/valaxy/ValaxyHamburger.vue')['default']
    ValaxyMd: typeof import('./components/valaxy/ValaxyMd.vue')['default']
    ValaxyOverlay: typeof import('./components/valaxy/ValaxyOverlay.vue')['default']
    ValaxyPagination: typeof import('./components/valaxy/ValaxyPagination.vue')['default']
    ValaxyPostCard: typeof import('./components/valaxy/ValaxyPostCard.vue')['default']
    ValaxyPostList: typeof import('./components/valaxy/ValaxyPostList.vue')['default']
    ValaxyRightSidebar: typeof import('./components/valaxy/ValaxyRightSidebar.vue')['default']
    ValaxySidebar: typeof import('./components/valaxy/ValaxySidebar.vue')['default']
    ValaxyToc: typeof import('./components/valaxy/ValaxyToc.vue')['default']
    YunBackToTop: typeof import('./components/yun/YunBackToTop.vue')['default']
    YunBanner: typeof import('./components/yun/YunBanner.vue')['default']
    YunBase: typeof import('./components/yun/YunBase.vue')['default']
    YunCard: typeof import('./components/yun/YunCard.vue')['default']
    YunCategories: typeof import('./components/yun/YunCategories.vue')['default']
    YunCategory: typeof import('./components/yun/YunCategory.vue')['default']
    YunConfig: typeof import('./components/yun/YunConfig.vue')['default']
    YunGirls: typeof import('./components/yun/YunGirls.vue')['default']
    YunGoDown: typeof import('./components/yun/YunGoDown.vue')['default']
    YunOverview: typeof import('./components/yun/YunOverview.vue')['default']
    YunPageHeader: typeof import('./components/yun/YunPageHeader.vue')['default']
    YunPostCollapse: typeof import('./components/yun/YunPostCollapse.vue')['default']
    YunPostMeta: typeof import('./components/yun/YunPostMeta.vue')['default']
    YunSay: typeof import('./components/yun/YunSay.vue')['default']
    YunSidebar: typeof import('./components/yun/YunSidebar.vue')['default']
    YunSidebarLinks: typeof import('./components/yun/YunSidebarLinks.vue')['default']
    YunSidebarNav: typeof import('./components/yun/YunSidebarNav.vue')['default']
    YunSocialLinks: typeof import('./components/yun/YunSocialLinks.vue')['default']
    YunSponsor: typeof import('./components/yun/YunSponsor.vue')['default']
  }
}

export {}
